[package]
name = "acm_detectors"
version.workspace = true
edition.workspace = true

[dependencies]
pyo3.workspace = true
numpy.workspace = true
ndarray.workspace = true
nalgebra.workspace = true
num-traits.workspace = true

[dev-dependencies]
approx = "0.5"
